function scope = build_cost_model_scope(hour,config)
%BUILD_COST_MODEL_SCOPE 明确标准 MATPOWER AC OPF 的成本项和未建模项。
settings=market_settings(config);
scope=table(hour,settings.marketMode,settings.bidMWMode,settings.priceFloor, ...
    settings.priceCap,true,true,true,false,false,false,false, ...
    "当前为逐小时 SCED/AC OPF：目标包含能量报价、计划偏差和弃电惩罚；不包含启停、停机、空载、最小开停机时间或跨时段机组组合。", ...
    'VariableNames',{'Hour','MarketMode','BidMWMode','PriceFloor','PriceCap', ...
    'IncludesEnergyBidCost','IncludesScheduleDeviationPenalty', ...
    'IncludesRenewableCurtailmentPenalty','IncludesStartupCost','IncludesShutdownCost', ...
    'IncludesNoLoadCost','IncludesMinUpDownConstraints','ModelScope'});
end
