function tables = empty_feasibility_recovery_tables(hour)
%EMPTY_FEASIBILITY_RECOVERY_TABLES 返回未运行恢复模型时的固定输出结构。
tables.summary=table(hour,false,"NotRun",nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"", ...
    'VariableNames',{'Hour','RecoverySuccess','RecoveryModel','RecoveryObjective', ...
    'RenewableCurtailmentMW','NuclearAbsoluteDeviationMW','LoadSheddingMW', ...
    'ExternalPurchaseMW','BranchLimitRelaxationMVA','CurtailmentPenalty', ...
    'NuclearDeviationPenalty','ValueOfLostLoad','ExternalPurchasePrice', ...
    'BranchViolationPenalty','RecoveryMessage'});
tables.load=table(zeros(0,1),false(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),'VariableNames',{'Hour','RecoverySuccess', ...
    'BusNo','OriginalLoadMW','ServedLoadMW','LoadSheddingMW','OriginalLoadMVAr', ...
    'ReactiveSheddingMVAr'});
tables.generator=build_market_schedule_performance(struct('gen',zeros(0,21)),struct(),hour,false);
tables.branch=table(zeros(0,1),false(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),'VariableNames',{'Hour','RecoverySuccess', ...
    'BranchRow','FromBus','ToBus','OriginalRateA','RequiredRelaxationMVA','ViolationCost'});
end
